// Catálogo de 35 videojuegos con imágenes estáticas mapeadas
export const gamesData = [
  {
    id: 1,
    title: "FIFA 26",
    category: "Deportes",
    price: 69.99,
    rating: 5.0,
    developer: "EA Sports",
    platforms: "PC / PS5 / XBOX Series X",
    emoji: "⚽",
    image: "/img/games/fifa-26.jpg",
    color: "#3a86c8",
    modelType: "trophy",
    description: "La simulación de fútbol definitiva de EA Sports. Vive la adrenalina del deporte rey con físicas de balón hiperrealistas, ligas internacionales actualizadas y los modos de juego de siempre como Ultimate Team y Carrera."
  },
  {
    id: 2,
    title: "Grand Theft Auto V",
    category: "Acción",
    price: 14.99,
    rating: 5.0,
    developer: "Rockstar Games",
    platforms: "PC / PS5 / PS4 / XBOX",
    emoji: "🚗",
    image: "/img/games/gta-v.jpg",
    color: "#38b000",
    modelType: "car",
    description: "Cuando un joven estafador callejero, un ladrón de bancos retirado y un psicópata aterrador se ven involucrados con lo peor del submundo criminal, deben realizar una serie de peligrosos golpes para sobrevivir."
  },
  {
    id: 3,
    title: "Rocket League",
    category: "Deportes",
    price: 0.00,
    rating: 4.0,
    developer: "Psyonix",
    platforms: "PC / PS5 / XBOX / Switch",
    emoji: "🏎️",
    image: "/img/games/rocket-league.jpg",
    color: "#00f2fe",
    modelType: "car",
    description: "Fútbol impulsado por cohetes. Conduce vehículos de alta potencia a través de estadios gigantes e intenta meter el balón metálico en la portería del rival. Un híbrido dinámico de caos de conducción y control preciso."
  },
  {
    id: 4,
    title: "The Crew 2",
    category: "Carreras",
    price: 1.50,
    rating: 4.0,
    developer: "Ubisoft",
    platforms: "PC / PS4 / XBOX",
    emoji: "🏍️",
    image: "/img/games/the-crew-2.jpg",
    color: "#ffb703",
    modelType: "car",
    description: "Conquista el escenario del motor americano por tierra, mar y aire en uno de los mundos abiertos de conducción más grandes jamás creados. Alterna al instante entre coches, motos, lanchas y aviones de acrobacias."
  },
  {
    id: 5,
    title: "Cyberpunk 2077",
    category: "Sci-Fi",
    price: 20.99,
    rating: 5.0,
    developer: "CD Projekt Red",
    platforms: "PC / PS5 / XBOX Series X",
    emoji: "🤖",
    image: "/img/games/cyberpunk-2077.jpg",
    color: "#ff007f",
    modelType: "shuriken",
    description: "Un RPG de acción y aventura en mundo abierto ambientado en Night City, una megalópolis obsesionada con el poder, el glamur y la modificación corporal. Juegas como V, un mercenario proscrito que busca un implante único."
  },
  {
    id: 6,
    title: "FNAF Into the Pit",
    category: "Acción",
    price: 17.99,
    rating: 4.0,
    developer: "Mega Cat Studios",
    platforms: "PC / PS5 / Switch / XBOX",
    emoji: "🐻",
    image: "/img/games/fnaf-into-the-pit.jpg",
    color: "#9d4edd",
    modelType: "voxel",
    description: "Salta a la piscina de bolas y viaja en el tiempo para salvar a tu padre en esta escalofriante aventura de horror en 2D y 3D basada en las famosas novelas de la saga de terror indie de Scott Cawthon."
  },
  {
    id: 7,
    title: "Fortnite",
    category: "Acción",
    price: 0.00,
    rating: 4.0,
    developer: "Epic Games",
    platforms: "PC / PS5 / XBOX / Switch / Mobile",
    emoji: "🔫",
    image: "/img/games/fortnite.jpg",
    color: "#39ff14",
    modelType: "shield",
    description: "Conviértete en el último superviviente en el Battle Royale gratuito de Epic Games. Construye forts, busca armas y enfréntate a otros 99 jugadores en una isla que cambia de temporada en temporada."
  },
  {
    id: 8,
    title: "Red Dead Redemption 2",
    category: "Acción",
    price: 14.99,
    rating: 5.0,
    developer: "Rockstar Games",
    platforms: "PC / PS5 / PS4 / XBOX",
    emoji: "🤠",
    image: "/img/games/red-dead-2.jpg",
    color: "#e63946",
    modelType: "shield",
    description: "La épica historia del forajido Arthur Morgan y la banda de Van der Linde a finales del siglo XIX. Cabalga por el salvaje oeste de Estados Unidos en una de las recreaciones de mundo abierto más aclamadas de la historia."
  },
  {
    id: 9,
    title: "Valorant",
    category: "Acción",
    price: 0.00,
    rating: 5.0,
    developer: "Riot Games",
    platforms: "PC / PS5 / XBOX",
    emoji: "🎯",
    image: "/img/games/valorant.jpg",
    color: "#d90429",
    modelType: "shuriken",
    description: "Un shooter táctico en primera persona 5v5 con personajes con habilidades únicas. Combina una puntería precisa con poderes estratégicos para plantar la Spike o defender tu territorio en rondas de alta tensión."
  },
  {
    id: 10,
    title: "Jurassic World Evolution 3",
    category: "Sci-Fi",
    price: 59.99,
    rating: 5.0,
    developer: "Frontier Developments",
    platforms: "PC / PS5 / XBOX",
    emoji: "🦖",
    image: "/img/games/jurassic-world-3.jpg",
    color: "#ffbe0b",
    modelType: "voxel",
    description: "Construye tu propio Parque Jurásico de ensueño en este simulador de gestión avanzado. Modifica el genoma de dinosaurios legendarios, crea hábitats seguros y sobrevive a desastres climáticos impredecibles."
  },
  {
    id: 11,
    title: "Lost Ark",
    category: "RPG",
    price: 0.00,
    rating: 4.0,
    developer: "Smilegate / Amazon",
    platforms: "PC",
    emoji: "🛡️",
    image: "/img/games/lost-ark.jpg",
    color: "#00b4d8",
    modelType: "shield",
    description: "Embárcate en una odisea por el vasto mundo de Arkesia en este MMO de acción. Explora continentes, navega por los mares, lucha contra jefes colosales y busca el poder de las Arcas perdidas para salvar tu mundo."
  },
  {
    id: 12,
    title: "Apex Legends",
    category: "Sci-Fi",
    price: 0.00,
    rating: 4.0,
    developer: "Respawn Entertainment",
    platforms: "PC / PS5 / XBOX / Switch",
    emoji: "🌌",
    image: "/img/games/apex-legends.jpg",
    color: "#ff007f",
    modelType: "spaceship",
    description: "El aclamado shooter Battle Royale de escuadrones ambientado en las Fronteras exteriores. Elige entre un catálogo de leyendas con personalidades y habilidades únicas en combates rápidos y competitivos."
  },
  {
    id: 13,
    title: "League of Legends",
    category: "Deportes",
    price: 0.00,
    rating: 5.0,
    developer: "Riot Games",
    platforms: "PC / Mac",
    emoji: "🔮",
    image: "/img/games/league-of-legends.jpg",
    color: "#9d4edd",
    modelType: "orb",
    description: "El MOBA competitivo de Riot Games que ha conquistado el mundo de los Esports. Dos equipos de de cinco campeones poderosos se enfrentan para destruir el Nexo del adversario en la mítica Grieta del Invocador."
  },
  {
    id: 14,
    title: "Dota 2",
    category: "Deportes",
    price: 0.00,
    rating: 5.0,
    developer: "Valve",
    platforms: "PC / Mac / Linux",
    emoji: "💥",
    image: "/img/games/dota-2.jpg",
    color: "#ff5400",
    modelType: "orb",
    description: "Lucha en la arena táctica de Valve en el MOBA más profundo y complejo. Con un plantel de más de cien héroes gratuitos disponibles desde el principio, domina estrategias complejas y compite en el circuito mundial."
  },
  {
    id: 15,
    title: "Team Fortress 2",
    category: "Deportes",
    price: 0.00,
    rating: 4.0,
    developer: "Valve",
    platforms: "PC / Mac",
    emoji: "🎩",
    image: "/img/games/team-fortress-2.jpg",
    color: "#ffbe0b",
    modelType: "trophy",
    description: "El clásico shooter multijugador cooperativo de Valve. Selecciona una de las 9 clases únicas (desde el veloz Scout hasta el fuerte Heavy) y compite en modos clásicos como Capturar la Bandera o Empujar la Vagoneta."
  },
  {
    id: 16,
    title: "Elden Ring",
    category: "RPG",
    price: 24.99,
    rating: 5.0,
    developer: "FromSoftware",
    platforms: "PC / PS5 / XBOX",
    emoji: "⚔️",
    image: "/img/games/elden-ring.jpg",
    color: "#ff5400",
    modelType: "sword",
    description: "Álzate, Sinluz, y déjate guiar por la Gracia para esgrimir el poder del Círculo de Elden en las Tierras Intermedias. Una aventura épica de rol y acción de FromSoftware escrita por Hidetaka Miyazaki y George R.R. Martin."
  },
  {
    id: 17,
    title: "AC Valhalla",
    category: "RPG",
    price: 19.99,
    rating: 4.0,
    developer: "Ubisoft",
    platforms: "PC / PS5 / XBOX",
    emoji: "🪓",
    image: "/img/games/ac-valhalla.jpg",
    color: "#39ff14",
    modelType: "shield",
    description: "Ponte en la piel de Eivor, una leyenda vikinga en busca de gloria. Explora un dinámico mundo abierto ambientado en la sombría Inglaterra de los años oscuros. Saquea asentamientos, funda tu clan y expande tu dominio."
  },
  {
    id: 18,
    title: "Baldur's Gate 3",
    category: "RPG",
    price: 29.99,
    rating: 5.0,
    developer: "Larian Studios",
    platforms: "PC / PS5 / XBOX",
    emoji: "🎲",
    image: "/img/games/baldurs-gate-3.jpg",
    color: "#9d4edd",
    modelType: "sword",
    description: "Reúne a tu grupo e inicia una campaña de rol inolvidable ambientada en el universo de Dungeons & Dragons. Un juego de rol de nueva generación con decisiones narrativas profundas y combate por turnos estratégico impecable."
  },
  {
    id: 19,
    title: "Starfield",
    category: "Sci-Fi",
    price: 22.49,
    rating: 4.0,
    developer: "Bethesda",
    platforms: "PC / XBOX Series X",
    emoji: "🚀",
    image: "/img/games/starfield.jpg",
    color: "#00f2fe",
    modelType: "spaceship",
    description: "El primer universo nuevo en 25 años de Bethesda Game Studios. Diseña tu personaje ideal, construye tu propia nave espacial y embárcate en un viaje interestelar para desvelar el mayor misterio de la humanidad."
  },
  {
    id: 20,
    title: "The Last of Us 2",
    category: "Acción",
    price: 27.99,
    rating: 5.0,
    developer: "Naughty Dog",
    platforms: "PS5 / PS4",
    emoji: "🌿",
    image: "/img/games/the-last-of-us-2.jpg",
    color: "#2a9d8f",
    modelType: "shield",
    description: "Cinco años después de su peligroso viaje por unos Estados Unidos pospandémicos, Ellie y Joel se asientan en Jackson. Sin embargo, un violento acontecimiento trunca la paz y Ellie emprende un implacable viaje de venganza."
  },
  {
    id: 21,
    title: "God of War Ragnarök",
    category: "Acción",
    price: 23.99,
    rating: 5.0,
    developer: "Santa Monica Studio",
    platforms: "PC / PS5 / PS4",
    emoji: "❄️",
    image: "/img/games/god-of-war-ragnarok.jpg",
    color: "#00f2fe",
    modelType: "sword",
    description: "Kratos y Atreus deben viajar a cada uno de los Nueve Reinos en busca de respuestas para prepararse para la batalla profetizada que acabará con el fin del mundo. Únete a ellos en este emotivo viaje de acción mitológica."
  },
  {
    id: 22,
    title: "Dying Light 2",
    category: "Acción",
    price: 19.99,
    rating: 4.0,
    developer: "Techland",
    platforms: "PC / PS5 / XBOX",
    emoji: "🧟",
    image: "/img/games/dying-light-2.jpg",
    color: "#ff5400",
    modelType: "shuriken",
    description: "El virus ganó y la humanidad está en las últimas. Explora La Ciudad en una época de supervivencia y parkour extremo. Utiliza habilidades físicas y armas modificadas para combatir contra bandas y mutantes nocturnos."
  },
  {
    id: 23,
    title: "Ghostwire Tokyo",
    category: "Sci-Fi",
    price: 25.49,
    rating: 4.0,
    developer: "Tango Gameworks",
    platforms: "PC / PS5 / XBOX",
    emoji: "👻",
    image: "/img/games/ghostwire-tokyo.jpg",
    color: "#9d4edd",
    modelType: "orb",
    description: "Enfréntate a lo desconocido en un Tokio donde la población ha desaparecido. Alíate con un detective fantasmal, domina artes de canalización de energía elemental y purga los espíritus malévolos que recorren las calles."
  },
  {
    id: 24,
    title: "Final Fantasy XVI",
    category: "RPG",
    price: 49.99,
    rating: 5.0,
    developer: "Square Enix",
    platforms: "PC / PS5",
    emoji: "🔥",
    image: "/img/games/final-fantasy-xvi.jpg",
    color: "#ff007f",
    modelType: "sword",
    description: "Una fantasía oscura donde el destino de la tierra está regido por los poderosos Eikons y los Emisarios que los controlan. Sigue la historia de Clive Rosfield en esta increíble entrega cargada de acción cinematográfica."
  },
  {
    id: 25,
    title: "Spider-Man 2",
    category: "Acción",
    price: 39.99,
    rating: 5.0,
    developer: "Insomniac Games",
    platforms: "PS5",
    emoji: "🕷️",
    image: "/img/games/spider-man-2.jpg",
    color: "#d90429",
    modelType: "shuriken",
    description: "Los Spider-Men Peter Parker y Miles Morales regresan para una nueva aventura. Balancéate, salta y planea por la Nueva York de Marvel, alternando entre ambos héroes para enfrentarse a villanos icónicos como Venom y Kraven."
  },
  {
    id: 26,
    title: "Hogwarts Legacy",
    category: "RPG",
    price: 45.99,
    rating: 4.0,
    developer: "Avalanche Software",
    platforms: "PC / PS5 / XBOX / Switch",
    emoji: "🪄",
    image: "/img/games/hogwarts-legacy.jpg",
    color: "#ffbe0b",
    modelType: "orb",
    description: "Un RPG de acción inmersivo en mundo abierto ambientado en el universo de los libros de Harry Potter en el siglo XIX. Conviértete en el mago o bruja que deseas ser, asiste a clases en Hogwarts y domina magia antigua."
  },
  {
    id: 27,
    title: "Tekken 8",
    category: "Deportes",
    price: 35.99,
    rating: 4.0,
    developer: "Bandai Namco",
    platforms: "PC / PS5 / XBOX Series X",
    emoji: "🥊",
    image: "/img/games/tekken-8.jpg",
    color: "#e63946",
    modelType: "trophy",
    description: "Prepárate para el siguiente capítulo de la legendaria saga de juegos de lucha de Bandai Namco. Con 32 luchadores rediseñados y el nuevo sistema de combate Heat, experimenta las batallas más intensas en 3D."
  },
  {
    id: 28,
    title: "Street Fighter 6",
    category: "Deportes",
    price: 34.99,
    rating: 4.0,
    developer: "Capcom",
    platforms: "PC / PS5 / PS4 / XBOX",
    emoji: "🥋",
    image: "/img/games/street-fighter-6.jpg",
    color: "#3a86c8",
    modelType: "trophy",
    description: "La evolución de los juegos de lucha de Capcom. Con tres modos de juego innovadores (World Tour, Fighting Ground y Battle Hub), Street Fighter 6 redefine el género de la lucha 2D con un estilo urbano y grafitero rompedor."
  },
  {
    id: 29,
    title: "Resident Evil 4",
    category: "Acción",
    price: 42.99,
    rating: 5.0,
    developer: "Capcom",
    platforms: "PC / PS5 / PS4 / XBOX",
    emoji: "👁️",
    image: "/img/games/resident-evil-4.jpg",
    color: "#228b22",
    modelType: "shield",
    description: "Seis años después del desastre biológico en Raccoon City, el agente Leon S. Kennedy es enviado a rescatar a la hija secuestrada del presidente de los EE. UU. en una aldea europea aislada donde acecha un horror inimaginable."
  },
  {
    id: 30,
    title: "Dragon Age Veilguard",
    category: "RPG",
    price: 36.99,
    rating: 4.0,
    developer: "BioWare",
    platforms: "PC / PS5 / XBOX Series X",
    emoji: "🐉",
    image: "/img/games/dragon-age-veilguard.jpg",
    color: "#9d4edd",
    modelType: "sword",
    description: "Reúne a la Guardia del Velo y desafía a los dioses corruptos en este RPG táctico de acción de BioWare. Forja amistades duraderas con compañeros expertos y salva a la tierra de Thedas del caos en una campaña narrativa rica."
  },
  {
    id: 31,
    title: "Returnal",
    category: "Sci-Fi",
    price: 38.99,
    rating: 4.0,
    developer: "Housemarque",
    platforms: "PC / PS5",
    emoji: "👩‍🚀",
    image: "/img/games/returnal.jpg",
    color: "#00f2fe",
    modelType: "spaceship",
    description: "Rompe el ciclo en este galardonado shooter roguelike en tercera persona. Tras estrellarse en Atropos, un planeta hostil que cambia de forma constantemente, Selene debe combatir por su vida y desvelar los secretos de su mente."
  },
  {
    id: 32,
    title: "S.T.A.L.K.E.R. 2",
    category: "Sci-Fi",
    price: 46.99,
    rating: 5.0,
    developer: "GSC Game World",
    platforms: "PC / XBOX Series X",
    emoji: "☣️",
    image: "/img/games/stalker-2.jpg",
    color: "#39ff14",
    modelType: "shield",
    description: "Explora la Zona de Exclusión de Chernóbil en un mundo abierto hostil, plagado de anomalías peligrosas, mutantes letales y facciones en guerra. Elige tu camino y desvela la verdad de este shooter inmersivo realista."
  },
  {
    id: 33,
    title: "Dragon's Dogma 2",
    category: "RPG",
    price: 41.99,
    rating: 4.0,
    developer: "Capcom",
    platforms: "PC / PS5 / XBOX Series X",
    emoji: "🦅",
    image: "/img/games/dragons-dogma-2.jpg",
    color: "#ff5400",
    modelType: "sword",
    description: "Embárcate en tu gran aventura como el Arisen en este RPG clásico de acción y fantasía en tercera persona. Crea a tu propio peón y enfréntate a monstruos gigantescos con físicas realistas en combates cooperativos únicos."
  },
  {
    id: 34,
    title: "Armored Core VI",
    category: "Sci-Fi",
    price: 31.99,
    rating: 4.0,
    developer: "FromSoftware",
    platforms: "PC / PS5 / PS4 / XBOX",
    emoji: "🤖",
    image: "/img/games/armored-core-vi.jpg",
    color: "#ff007f",
    modelType: "spaceship",
    description: "Combates vertiginosos con robots gigantes y blindados de FromSoftware. Diseña y personaliza tu propio meca con armas devastadoras y lucha contra corporaciones rivales por el control de una sustancia energética en Rubicón 3."
  },
  {
    id: 35,
    title: "Metaphor ReFantazio",
    category: "RPG",
    price: 37.99,
    rating: 5.0,
    developer: "Atlus",
    platforms: "PC / PS5 / XBOX",
    emoji: "📖",
    image: "/img/games/metaphor-refantazio.jpg",
    color: "#9d4edd",
    modelType: "sword",
    description: "De los creadores de Persona 3, 4 y 5, adéntrate en un mundo de fantasía único en este profundo RPG por turnos y acción. Compite en el torneo por el trono real y viaja en tu gauntlet runner para salvar al reino."
  }
];

// Planes de Suscripción extraídos de suscripciones.json de DAW
export const subscriptionsData = [
  {
    id: "free",
    title: "PLAN FREE",
    priceMonthly: 0,
    priceAnnual: 0,
    features: [
      "Acceso a juegos gratis",
      "Lista de favoritos básicos",
      "Publicidad holográfica sutil"
    ],
    color: "#94a3b8", // Slate
    modelType: "cube",
    emoji: "🧊",
    description: "Prueba completa y gratuita de nuestro portal de juegos en la red de datos Nebula. Perfecto para jugar a los títulos Free-to-Play sin coste alguno."
  },
  {
    id: "pro",
    title: "PLAN PRO",
    priceMonthly: 9.99,
    priceAnnual: 79.92,
    features: [
      "Todo lo de Free",
      "500+ juegos exclusivos de la biblioteca",
      "20% de descuento automático en ofertas",
      "Descargas neurales ilimitadas"
    ],
    color: "#00f2fe", // Cyan
    modelType: "orbital",
    emoji: "🪐",
    recommended: true,
    description: "El plan idóneo para la mayoría de los jugadores estelares. Incluye una amplia biblioteca de títulos con un descuento automático del 20% en tus compras."
  },
  {
    id: "premium",
    title: "PLAN PREMIUM",
    priceMonthly: 14.99,
    priceAnnual: 119.92,
    features: [
      "Todo lo de Pro",
      "1000+ juegos y expansión de catálogo",
      "35% de descuento automático en ofertas",
      "Acceso a juegos de estreno en Día 1",
      "Soporte holográfico prioritario 24/7"
    ],
    color: "#3a86c8", // Blue
    modelType: "diamond",
    emoji: "💎",
    description: "La experiencia completa de ocio espacial. Juega a los nuevos lanzamientos el primer día con un 35% de descuento y la máxima velocidad de descarga."
  },
  {
    id: "vip",
    title: "PLAN VIP",
    priceMonthly: 19.99,
    priceAnnual: 159.92,
    features: [
      "Todo lo de Premium",
      "Catálogo ilimitado en la nube (10000+)",
      "50% de descuento en todos los títulos",
      "Acceso anticipado a Betas exclusivas",
      "Eventos multijugador VIP privados"
    ],
    color: "#9d4edd", // Purple
    modelType: "crown",
    emoji: "👑",
    badge: "⭐ MÁXIMO AHORRO",
    description: "El estatus definitivo en la galaxia. Consigue un 50% de descuento en todas las compras del catálogo y el máximo abanico de privilegios de acceso beta."
  }
];

// Usuarios de prueba extraídos de suscripciones.json
export const mockUsers = [
  {
    email: "juan@email.com",
    name: "Juan García",
    plan: "pro",
    billingMode: "monthly",
    discount: 0.20
  },
  {
    email: "maria@email.com",
    name: "María López",
    plan: "vip",
    billingMode: "annual",
    discount: 0.50
  },
  {
    email: "carlos@email.com",
    name: "Carlos Martínez",
    plan: "free",
    billingMode: "monthly",
    discount: 0.00
  }
];
